version: '3.8'

services:
  db:
    container_name: db
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: nutriu
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    container_name: nutriu
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/nutriu-api
      - /nutriu-api/node_modules
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=secret
      - DB_NAME=nutriu
      - DB_PORT=5432
    command: /bin/sh -c "sleep 10 && npm run dev"

volumes:
  postgres_data: