version: '3.8'

services:
  app:
    container_name: node_app
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/nutriu-api
      - /nutriu-api/node_modules
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=mydatabase
      - DB_PORT=5432

  db:
    container_name: postgres_db
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: