enum NutrientType {
  MOISTURE = "moisture",
  KCAL = "kcal",
  KJ = "kJ",
  PROTEIN = "protein",
  LIPIDS = "lipids",
  CHOLESTEROL = "cholesterol",
  CARBOHYDRATES = "carbohydrates",
  DIETARY_FIBER = "dietaryFiber",
  ASH = "ash",
  CALCIUM = "calcium",
  MAGNESIUM = "magnesium",
  MANGANESE = "manganese",
  PHOSPHORUS = "phosphorus",
  IRON = "iron",
  SODIUM = "sodium",
  POTASSIUM = "potassium",
  COPPER = "copper",
  ZINC = "zinc",
  RETINOL = "retinol",
  RE = "re",
  RAE = "rae",
  THIAMIN = "thiamin",
  RIBOFLAVIN = "riboflavin",
  PYRIDOXINE = "pyridoxine",
  NIACIN = "niacin",
  VITAMIN_C = "vitaminC",
}

export default NutrientType;
export const NutrientTypeValues = Object.values(NutrientType);
